---
- name: Install dependencies for CentOS
  apt:
    name: '{{ item }}'
    state: installed
    force: yes
    update_cache: yes
    cache_valid_time: 3600
  with_items:
      - make
      - git
      - gcc
      - libssl-dev
      - libreadline-dev
      - zlib1g-dev
  become: true
