---
- name: Install dependencies for {{ ansible_os_family }}
  yum:
    name: '{{ item }}'
    state: installed
    update_cache: yes
  with_items:
      - git
      - zlib
      - zlib-devel
      - gcc-c++
      - patch
      - readline
      - readline-devel
      - libyaml-devel
      - libffi-devel
      - openssl-devel
      - make
      - bzip2
      - autoconf
      - automake
      - libtool
      - bison
      - curl
      - sqlite-devel
  become: true
