---
- name: Check for previous installation of {{ item.name }}
  stat:
    path: '{{ rbenv.path }}/plugins/{{ item.name }}'
  ignore_errors: true
  register: plugin_dir

- name: Clone {{ item.name }}
  git:
    repo: '{{ item.repo }}'
    dest: '{{ rbenv.path }}/plugins/{{ item.name }}'

  when: plugin_dir.stat.exists == false

- name: Create default gems list
  template:
    src: templates/default-gems.j2
    dest: '{{ rbenv.path }}/default-gems'
  become: true
  become_user: '{{ ansible_user_id }}'
  when: item.name == 'rbenv-default-gems'
