---
- name: Check for {{ ruby_version }}
  stat:
    path: '{{ rbenv_path }}/versions/{{ ruby_version }}'
  register: ruby
  ignore_errors: yes

- name: Install ruby {{ ruby_version }}
  raw: 'RBENV_ROOT={{ rbenv_path }} {{ rbenv_path }}/bin/rbenv install {{ ruby_version }}'
  notify: rehash
  when: ruby.stat.exists == false
