---
- name: Check for previous installation of rbenv
  stat:
    path: '{{ rbenv.path }}/bin/rbenv'
  ignore_errors: true
  register: rbenv_bin

- block:
  - name: Create base directory
    file:
      path: '{{ rbenv.path }}'
      state: directory
      group: '{{ remote_user | default(ansible_user_id) }}'
      owner: '{{ remote_user | default(ansible_user_id) }}'
    become: true

  - name: Clone rbenv
    git:
      repo: '{{ rbenv.repo }}'
      dest: '{{ rbenv.path }}'
      accept_hostkey: yes

  - name: Compile dynamic bash extension to speed up rbenv
    raw: '{{ rbenv.path }}/src/configure && make -C {{ rbenv.path }}/src'

  - name: Add rbenv to PATH
    template:
      src: rbenv.sh.j2
      dest: /etc/profile.d/rbenv.sh
      owner: root
      group: root
      mode: 0775
    become: true
  when: rbenv_bin.stat.exists == false
